"""piches and feedbacks updated

Revision ID: 71fe7fc4e72c
Revises: 6848dd3aba1d
Create Date: 2019-02-13 17:35:38.144410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fe7fc4e72c'
down_revision = '6848dd3aba1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###
